//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementAutomation.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAbout
    {
        public int ID { get; set; }
        public string About1 { get; set; }
        public string About2 { get; set; }
        public string About3 { get; set; }
        public string About4 { get; set; }
    }
}
