//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementAutomation.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCashRegister
    {
        public int CashRegisterID { get; set; }
        public string CashRegisterName { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Income { get; set; }
        public Nullable<decimal> Expense { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual TblStatu TblStatu { get; set; }
    }
}
