//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementAutomation.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProduct
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductGroup { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<byte> Tax { get; set; }
        public Nullable<int> Staff { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual TblProductGroup TblProductGroup { get; set; }
        public virtual TblStatu TblStatu { get; set; }
        public virtual TblStockUnit TblStockUnit { get; set; }
    }
}
