//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementAutomation.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblReservation
    {
        public int ReservationID { get; set; }
        public Nullable<int> Guest { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public string NumberOfPeople { get; set; }
        public Nullable<int> Room { get; set; }
        public string ReservationNameSurname { get; set; }
        public string Phone { get; set; }
        public string Statement { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Person1 { get; set; }
        public Nullable<int> Person2 { get; set; }
        public Nullable<int> Person3 { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<bool> ToTheCashResgiter { get; set; }
    
        public virtual TblGuest TblGuest { get; set; }
        public virtual TblRoom TblRoom { get; set; }
        public virtual TblStatu TblStatus { get; set; }
    }
}
